import math
import inspect

cf = inspect.currentframe()

x = math.sqrt(64)

print(f'{inspect.getframeinfo(cf).lineno}: {math.sqrt(64)}')

x = math.ceil(1.4)
y = math.floor(1.4)
z = math.floor(-1.4)

print(f'{inspect.getframeinfo(cf).lineno}: {x}')
print(f'{inspect.getframeinfo(cf).lineno}: {y}')

print(f'{inspect.getframeinfo(cf).lineno}: {math.pi}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.pi/2.0}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.radians(90)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.sin(math.pi/2.0)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.cos(math.pi/4.0)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.asin(1)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.acos(0)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.comb(3,2)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.perm(3,2)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.copysign(-4, 5)}')
p = (1,1)
q = (4,5)
print(f'{inspect.getframeinfo(cf).lineno}: {math.dist(p,q)}')
p = (1,1,1)
q = (4,4,4)
print(f'{inspect.getframeinfo(cf).lineno}: {math.dist(p,q)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.erf(5)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.exp(1)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.expm1(1)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.fabs(-2.341)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.fmod(3.2,2.1)}')
x = [1.1,2.2,3.3]
print(f'{inspect.getframeinfo(cf).lineno}: {math.fsum(x)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.gcd(36,6)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.isfinite(1234567890)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.tan(math.pi/2)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.isinf(math.tan(math.pi/2))}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.isnan(3)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.isqrt(12)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.ldexp(5,2)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.log(3, 10)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.pow(10, 0.47712125471966244)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.log10(3)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.modf(5.25)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.remainder(3,14)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.sqrt(16)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.factorial(4)}')
print(f'{inspect.getframeinfo(cf).lineno}: {math.e}')
